#include "ofApp.h"

void ofApp::DeepDream() {
    
    s = slideshow.addSlide("\"Image generated by a convolutional neural network\"");
    s->addImage("reddit deepdream post", "/Users/gene/bin/deepdream/reddit.png", 0.0, 0.1, 0.7, 1);
    s->addImage("reddit image", "/Users/gene/bin/deepdream/_slugs.jpg", 0.45, 0, 0.55, 0.4);
    s->addText(h3, ofColor(0), "Mysteriously posted to /r/MachineLearning on June 16, 2015", 0.00, 0.0, 0.38);
    
    //    http://www.evolvingai.org/content/ai-neuroscience-understanding
    
    s = slideshow.addSlide("Google Inceptionism classvis");
    s->addImage("Deepdream classvis", "/Users/gene/bin/deepdream/paper/classvis.png", 0.0, 0.2, 1, 0.8);
    s->addText(h4, ofColor(0), "Going deeper with Inceptionism (Mordvintsev, Olah, Tyka)", 0.2, 0.0, 1.0);
    s->addText(h4, ofColor(0), "googleresearch.blogspot.com/2015/06/inceptionism-going-deeper-into-neural.html]", 0.2, 0.1, 1.0);
    
    s = slideshow.addSlide("Deepdream");
    s->addImage("Ibis", "/Users/gene/bin/deepdream/paper/ibis.png", 0.0, 0.0, 1.0, 0.65);
    s->addImage("Deepdream prototypes", "/Users/gene/bin/deepdream/paper/Funny-Animals.png", 0.0, 0.66, 1.0, 0.33);
    s->addText(h4, ofColor(0), "googleresearch.blogspot.com/2015/06/inceptionism-going-deeper-into-neural.html]", 0.04, 0.0, 1.0);
    
    s = slideshow.addSlide("Deepdream noise");
    s->addImage("Tyka noisedream 1", "/Users/gene/bin/deepdream/paper/building-dreams1.png", 0.0, 0.0, 0.5, 1.0);
    s->addImage("Tyka noisedream 2", "/Users/gene/bin/deepdream/paper/building-dreams2.png", 0.5, 0.0, 0.5, 1.0);
    s->addText(h3, ofColor(0), "Mike Tyka [mtyka.github.io]", 0.15, 0.0, 1.0);
    
    s = slideshow.addSlide("Deepdream: Vishnu");
    s->addImage("vishnu", "/Users/gene/bin/deepdream/gods/_vishnu2.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("vishnu deepdream", "/Users/gene/bin/deepdream/gods/vishnu(2)__12_3_1.2(1).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("vishnu deepdream", "/Users/gene/bin/deepdream/gods/vishnu(2)__12_3_1.2(10).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("vishnu deepdream", "/Users/gene/bin/deepdream/gods/vishnu(2)__12_3_1.2(23).jpg", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Charles Monet");
    s->addImage("Monet", "/Users/gene/bin/deepdream/painters/_monet1.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Monet", "/Users/gene/bin/deepdream/painters/monet1(1)0002_i10_o4_os1.1_j32.png", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Egon Schiele");
    s->addImage("Schiele", "/Users/gene/bin/deepdream/painters/_schiele.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Schiele", "/Users/gene/bin/deepdream/painters/schiele(0)0002_i10_o4_os1.1_j32.png", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Schiele", "/Users/gene/bin/deepdream/painters/schiele(1)0001_i10_o4_os1.1_j32.png", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Edvard Munch");
    s->addImage("Munch", "/Users/gene/bin/deepdream/painters/_scream.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Munch", "/Users/gene/bin/deepdream/painters/scream_0029_i10_o4_os1.4_j32.png", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Fireworks");
    s->addImage("July 4 Fireworks", "/Users/gene/bin/deepdream/fireworks/_fireworks.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("July 4 Fireworks", "/Users/gene/bin/deepdream/fireworks/fireworks1_10_4_1.4(5).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("July 4 Fireworks", "/Users/gene/bin/deepdream/fireworks/fireworks1a_10_8_1.4(2).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("July 4 Fireworks", "/Users/gene/bin/deepdream/fireworks/fireworks2a_10_8_1.4(9).jpg", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Lake Indawgyi");
    s->addImage("lake indawgyi", "/Users/gene/bin/deepdream/holy_places/_indawgyi_pagoda.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("lake indawgyi deepdream", "/Users/gene/bin/deepdream/holy_places/indawgyi_pagoda_10_4_1.4(6).jpg", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Jaaga");
    s->addImage("Jaaga", "/Users/gene/bin/deepdream/jaaga/_jaaga.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Jaaga", "/Users/gene/bin/deepdream/jaaga/jaaga_1_8_4_1.4(13).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Jaaga", "/Users/gene/bin/deepdream/jaaga/jaaga(2)__10_4_1.4(5).jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Jaaga", "/Users/gene/bin/deepdream/jaaga/jaaga(2)__16_5_1.2(11).jpg", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepdream: Leonardo Da Vinci");
    s->addImage("Da Vinci", "/Users/gene/bin/deepdream/painters/_davinci.jpg", 0, 0, 1, 1);
    s->addBreakpoint();
    s->addImage("Da Vinci", "/Users/gene/bin/deepdream/painters/davinci_drawing(0)0002_i5_o8_os1.1_j32.png", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Deepzoom");
    s->addMovie("Deepzoom", "/Users/gene/bin/deepdream/video_feedback/deepzoom.mp4", true, 0, 0, 1, 1);
    
    s = slideshow.addSlide("Oscillating which layer to enhance");
    s->addMovie("Deepzoom", "/Users/gene/bin/deepdream/video_content/deeptrain2.mp4", true, 0.0, 0.0, 0.6, 0.35);
    s->addMovie("Deepzoom", "/Users/gene/bin/deepdream/video_prototypes/testOtherl4_1.mp4", true, 0.0, 0.35, 0.5, 0.65);
    s->addMovie("Deepzoom", "/Users/gene/bin/deepdream/video_prototypes/makeMid_blur_2a_imovie.mp4", true, 0.4, 0.0, 0.6, 0.6);
    s->addMovie("Deepzoom", "/Users/gene/bin/deepdream/video_feedback/theFrame7.mp4", true, 0.5, 0.5, 0.5, 0.5);
    
    s = slideshow.addSlide("Inceptionism class visualizations (Kyle McDonald)");
    s->addScrollableImage("deepdream class vis", "/Users/gene/bin/misc/stock/kcimc_deepdream_classvis1.png", 0, 0.0, 1, 1.0);
    
    s = slideshow.addSlide("Inceptionism class visualizations (Kyle McDonald)");
    s->addScrollableImage("deepdream class vis", "/Users/gene/bin/misc/stock/kcimc_deepdream_classvis2.png", 0, 0.0, 1, 1.0);
    
    s = slideshow.addSlide("Classvis by Mike Tyka (leatherback turtle");
    s->addImage("tyka", "/Users/gene/bin/misc/stock/mtyka_deepdream1_leatherbackturtles.jpg", 0, 0, 1, 1);
    
    s = slideshow.addSlide("Classvis by Mike Tyka (pelican");
    s->addImage("tyka", "/Users/gene/bin/misc/stock/mtyka_deepdream_pelican.jpg", 0, 0, 1, 1);
    
    slideshow.addSlide("Make it stop")->addImage("cappucinno", "/Users/gene/bin/deepdream/cappucinno/composite_cappucinno2a.png", 0.05, 0.05, 0.9, 0.9);
}
